<a href="https://colab.research.google.com/github/Yashaswi04/Data-Science--VCET/blob/main/Pandas_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

print("Array is of type: ", type(arr))


print("No. of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:

import numpy as np


arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)


arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [ ]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])

c = arr.copy()

print("id of arr", id(arr))
print("id of c", id(c))


arr[0] = 12

print("original array- ", arr)
print("copy- ", c)

id of arr 137586081556560
id of c 137586066728656
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:

def sum(array):


	sum = 0

	for i in array:

		sum += i


	return sum


testArray = [1, 3, 34, 92, 29, 48, 20.3]


print('The sum of your numbers is ' + str(sum(testArray)))

The sum of your numbers is 227.3


In [ ]:
import numpy as np

a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)

newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:

import numpy


x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])


print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))


print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:

import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:

import pandas as pd

print(pd.__version__)

2.0.3


In [ ]:



import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)


print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [ ]:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df)


print(df.loc[0])

print(df.loc[[0, 1]])


   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

# New section

# New section

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)



FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
import pandas as pd

print(pd.options.display.max_rows)


60


In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')

print(df)

print(pd.options.display.max_rows)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [ ]:

import pandas as pd


df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)


df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")



'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [ ]:

import pandas as pd

df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)


df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)


display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [ ]:

import pandas as pd


df = pd.read_csv("nba.csv")


print(df.head())



FileNotFoundError: [Errno 2] No such file or directory: 'nba.csv'

In [ ]:

gk = df.groupby('Team')

gk.first()

KeyError: 'Team'

In [ ]:

gk.get_group('Boston Celtics')

NameError: name 'gk' is not defined

In [ ]:

j = 1

while(j<= 5):
	print(j)
	j = j + 1


1
2
3
4
5
